# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='avatar/%Y/%m/%d/')),
                ('filepath', models.CharField(max_length=128, verbose_name='\u6587\u4ef6\u8def\u5f84')),
            ],
        ),
        migrations.CreateModel(
            name='WXfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=128, verbose_name='\u5fae\u4fe1\u6587\u4ef6id')),
                ('relatetype', models.CharField(max_length=128, verbose_name='\u5173\u8054\u5143\u7d20\u7c7b\u578b')),
                ('relateid', models.CharField(max_length=128, verbose_name='\u5173\u8054\u5143\u7d20id')),
            ],
        ),
    ]
