# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-29 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='WXfile',
        ),
    ]
