# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_wxfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxfile',
            name='remark',
            field=models.CharField(max_length=128, null=True, verbose_name='\u8bed\u97f3\u6587\u5b57'),
        ),
    ]
