# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchEngineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5206\u90e8\u540d\u79f0')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.BranchEngineering', verbose_name='\u7236\u5de5\u7a0b')),
            ],
            options={
                'db_table': 'diary_branch_engineering',
                'verbose_name': '\u5206\u90e8\u5de5\u7a0b',
                'verbose_name_plural': '\u5206\u90e8\u5206\u9879',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u57ce\u5e02\u540d\u79f0')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.City', verbose_name='\u6240\u5c5e\u533a\u57df')),
            ],
            options={
                'db_table': 'diary_city',
                'verbose_name': '\u7701\u5e02\u53bf',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('introduction', models.CharField(blank=True, max_length=256, verbose_name='\u516c\u53f8\u7b80\u4ecb')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Company', verbose_name='\u6bcd\u516c\u53f8')),
            ],
            options={
                'db_table': 'diary_company',
                'verbose_name': '\u516c\u53f8\u5355\u4f4d',
                'verbose_name_plural': '\u516c\u53f8',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6\xe5\x90\x8d')),
                ('shortname', models.CharField(max_length=128, verbose_name=b'\xe7\xae\x80\xe5\x86\x99')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('filepath', models.CharField(max_length=128, verbose_name=b'\xe6\x96\x87\xe4\xbb\xb6\xe8\xb7\xaf\xe5\xbe\x84')),
                ('filesize', models.FloatField(blank=True, null=True, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
                ('filetype', models.CharField(choices=[(b'WD', b'\xe5\x8d\xb1\xe5\xa4\xa7\xe5\xb7\xa5\xe7\xa8\x8b'), (b'GX', b'\xe9\x87\x8d\xe7\x82\xb9\xe5\xb7\xa5\xe5\xba\x8f'), (b'XM', b'\xe9\xa1\xb9\xe7\x9b\xae')], max_length=20)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e0a\u4f20\u8005')),
            ],
            options={
                'db_table': 'diary_document',
                'verbose_name': '\u6587\u4ef6',
                'verbose_name_plural': '\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u540d\u79f0')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5730\u5740')),
                ('insert_dt', models.DateField(blank=True, null=True, verbose_name='\u8bb0\u5f55\u65e5\u671f')),
                ('area', models.FloatField(blank=True, null=True, verbose_name=b'\xe9\x9d\xa2\xe7\xa7\xaf')),
                ('height', models.FloatField(blank=True, null=True, verbose_name=b'\xe9\xab\x98\xe5\xba\xa6')),
                ('struct_type', models.IntegerField(blank=True, default=1, null=True, verbose_name='\u7ed3\u6784\u7c7b\u578b')),
                ('shiji_schedule', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5b9e\u9645\u8fdb\u5ea6')),
                ('design_schedule', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u8ba1\u5212\u8fdb\u5ea6')),
                ('branchengineering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.BranchEngineering', verbose_name='\u5206\u90e8\u5de5\u7a0b')),
            ],
            options={
                'db_table': 'diary_engineering',
                'verbose_name': '\u5355\u4f4d\u5de5\u7a0b',
                'verbose_name_plural': '\u5de5\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='JSFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoid', models.CharField(blank=True, max_length=64, verbose_name='\u4e1a\u52a1\u7f16\u7801')),
                ('FAMC', models.CharField(blank=True, max_length=64, verbose_name='\u65b9\u6848\u540d\u79f0')),
                ('FABH', models.CharField(blank=True, max_length=64, verbose_name='\u65b9\u6848\u7f16\u53f7')),
                ('FAID', models.CharField(blank=True, max_length=64, verbose_name='\u65b9\u6848ID')),
                ('FALB', models.CharField(blank=True, max_length=64, verbose_name='\u65b9\u6848\u7c7b\u522b')),
                ('PrjName', models.CharField(blank=True, max_length=200, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('PrjId', models.CharField(blank=True, max_length=100, verbose_name='\u9879\u76ee\u7f16\u53f7')),
                ('GCGS', models.CharField(blank=True, max_length=64, verbose_name='\u5de5\u7a0b\u516c\u53f8')),
                ('GCGSID', models.CharField(blank=True, max_length=64, verbose_name='\u5de5\u7a0b\u516c\u53f8\u7f16\u7801')),
                ('GCLB', models.CharField(blank=True, max_length=64, verbose_name='\u5de5\u7a0b\u7c7b\u522b')),
                ('sgzt', models.CharField(blank=True, max_length=64, verbose_name='\u65bd\u5de5\u72b6\u6001')),
                ('jhbzrq', models.DateTimeField(blank=True, null=True, verbose_name='\u8ba1\u5212\u7f16\u5236\u65e5\u671f')),
                ('xcssrq', models.DateTimeField(blank=True, null=True, verbose_name='\u73b0\u573a\u65bd\u5de5\u65e5\u671f')),
                ('xcjsrq', models.DateTimeField(blank=True, null=True, verbose_name='\u73b0\u573a\u7ed3\u675f\u65e5\u671f')),
                ('BZRQ', models.DateTimeField(blank=True, null=True, verbose_name='\u7f16\u5236\u65e5\u671f')),
                ('bzr', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f16\u5236\u4eba')),
                ('BZ', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u662f\u5426\u7f16\u5236')),
                ('xmgcs', models.CharField(blank=True, max_length=64, verbose_name='\u9879\u76ee\u5de5\u7a0b\u5e08')),
                ('xmjl', models.CharField(blank=True, max_length=64, verbose_name='\u9879\u76ee\u7ecf\u7406')),
                ('JSDW', models.CharField(blank=True, max_length=64, verbose_name='\u5efa\u8bbe\u5355\u4f4d')),
                ('sfba1', models.CharField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], max_length=64, verbose_name='\u662f\u5426\u5907\u6848')),
                ('sfzdwxy', models.CharField(blank=True, max_length=64, verbose_name='\u662f\u5426\u91cd\u5927\u5371\u9669\u6e90')),
                ('sfzjlz', models.CharField(blank=True, max_length=64, verbose_name='\u662f\u5426\u4e13\u5bb6\u8ba4\u8bc1')),
                ('C_BizRangeId', models.CharField(blank=True, max_length=64, verbose_name='\u5de5\u7a0b\u7f16\u7801')),
                ('insert_dt', models.DateTimeField(blank=True, null=True, verbose_name='\u8bb0\u5f55\u65e5\u671f')),
                ('schedule', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8fdb\u5ea6')),
                ('jiaodi_status', models.CharField(blank=True, default=b'\xe5\x90\xa6', max_length=64, verbose_name='\u4ea4\u5e95\u72b6\u6001')),
            ],
            options={
                'ordering': ('-insert_dt',),
                'db_table': 'diary_JSFA',
                'verbose_name': '\u5371\u5927\u5de5\u7a0b',
                'verbose_name_plural': '\u5371\u5927',
            },
        ),
        migrations.CreateModel(
            name='JSFAFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.IntegerField(blank=True, default=1, verbose_name='\u56fe\u7247\u7c7b\u578b')),
                ('danger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.JSFA', verbose_name='\u5371\u5927')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Document', verbose_name='\u6587\u4ef6')),
            ],
            options={
                'db_table': 'diary_JSFA_file',
                'verbose_name': '\u5371\u5927\u6587\u4ef6',
                'verbose_name_plural': '\u5371\u5927\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u540d\u79f0')),
                ('addtime', models.DateField(blank=True, null=True, verbose_name='\u65e5\u671f')),
                ('end_dt', models.DateField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('gxtype', models.IntegerField(blank=True, choices=[(1, '\u91cd\u70b9\u5de5\u5e8f'), (2, '\u5173\u952e\u5de5\u5e8f'), (3, '\u96be\u70b9\u5de5\u5e8f')], null=True, verbose_name='\u5de5\u5e8f\u7c7b\u578b')),
                ('status', models.IntegerField(blank=True, choices=[(1, '\u672a\u5ba1\u6279'), (2, '\u5ba1\u6838\u4e2d'), (3, '\u5df2\u7ed3\u675f')], null=True, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('bianzhi', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f16\u5236')),
                ('jiankong', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u76d1\u63a7')),
                ('schedule', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8fdb\u5ea6')),
                ('branch_engeering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.BranchEngineering', verbose_name='\u6240\u5c5e\u5206\u9879')),
                ('engineering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineerprocedures', to='Projects.Engineering', verbose_name='\u6240\u5c5e\u5de5\u7a0b')),
            ],
            options={
                'ordering': ('-addtime',),
                'db_table': 'diary_procedure',
                'verbose_name': '\u5de5\u5e8f\u7ba1\u63a7',
                'verbose_name_plural': '\u5de5\u5e8f',
            },
        ),
        migrations.CreateModel(
            name='ProcedureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Document', verbose_name='\u6587\u4ef6')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Procedure', verbose_name='\u5de5\u5e8f')),
            ],
            options={
                'db_table': 'diary_procedure_file',
                'verbose_name': '\u5de5\u5e8f\u6587\u4ef6',
                'verbose_name_plural': '\u5de5\u5e8f\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrjId', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9879\u76eeID')),
                ('PrjName', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('GCGS', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6240\u5c5e\u5de5\u7a0b\u516c\u53f8')),
                ('GCGSID', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u6240\u5c5e\u516c\u53f8\u7f16\u53f7')),
                ('PrjSFLX', models.IntegerField(choices=[(0, '\u672a\u7acb\u9879'), (1, '\u5df2\u7acb\u9879')], default=0, verbose_name='\u662f\u5426\u7acb\u9879')),
                ('PrjState', models.IntegerField(blank=True, choices=[(0, '\u7ae3\u5de5'), (1, '\u5728\u5efa')], null=True, verbose_name='\u9879\u76ee\u72b6\u6001')),
                ('gldw', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7ba1\u7406\u5355\u4f4d')),
                ('jsdw', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5efa\u8bbe\u5355\u4f4d')),
                ('sjdw', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8bbe\u8ba1\u5355\u4f4d')),
                ('kcdw', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u52d8\u5bdf\u5355\u4f4d')),
                ('jldw', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u76d1\u7406\u5355\u4f4d')),
                ('zbdw', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u603b\u5305\u5355\u4f4d')),
                ('KGRQ', models.DateField(blank=True, null=True, verbose_name='\u5f00\u5de5\u65e5\u671f')),
                ('JGRQ', models.DateField(blank=True, null=True, verbose_name='\u7ae3\u5de5\u65e5\u671f')),
                ('XMGCS', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9879\u76ee\u5de5\u7a0b\u5e08')),
                ('XMGCSID', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9879\u76ee\u5de5\u7a0b\u5e08ID')),
                ('XMJL', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9879\u76ee\u7ecf\u7406')),
                ('XMJLID', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9879\u76ee\u7ecf\u7406ID')),
                ('latitude', models.CharField(blank=True, max_length=24, null=True)),
                ('longitude', models.CharField(blank=True, max_length=24, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u9879\u76ee\u5730\u5740')),
                ('area', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe9\x9d\xa2\xe7\xa7\xaf')),
                ('price', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe9\x80\xa0\xe4\xbb\xb7')),
                ('quality_target', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u8d28\u91cf\u76ee\u6807')),
                ('safe_target', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5b89\u5168\u76ee\u6807')),
                ('environment_target', models.CharField(blank=True, max_length=256, verbose_name='\u73af\u5883\u76ee\u6807')),
                ('pact_target', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5408\u540c\u76ee\u6807')),
                ('project_target', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u9879\u76ee\u76ee\u6807')),
                ('culture_target', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u65bd\u5de5\u6587\u660e\u76ee\u6807')),
                ('deep', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe6\xb7\xb1\xe5\xba\xa6')),
                ('height', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'\xe9\xab\x98\xe5\xba\xa6')),
                ('danti_nums', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5355\u4f53\u6570\u91cf')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.City', verbose_name='\u57ce\u5e02')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectlist', to='Projects.Company', verbose_name='\u516c\u53f8\u5355\u4f4d')),
            ],
            options={
                'db_table': 'diary_project',
                'verbose_name': '\u9879\u76ee\u8868',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField(blank=True, default=1, verbose_name='\u56fe\u7247\u7c7b\u578b')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Document', verbose_name='\u6587\u4ef6')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Project', verbose_name='\u9879\u76ee')),
            ],
            options={
                'db_table': 'diary_project_file',
                'verbose_name': '\u9879\u76ee\u6587\u4ef6',
                'verbose_name_plural': '\u9879\u76ee\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=64, verbose_name='\u6e29\u5ea6')),
                ('weather', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5929\u6c14')),
                ('qualitys', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u8d28\u91cf')),
                ('safetys', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5b89\u5168')),
                ('fieldcapacitys', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u573a\u5bb9')),
                ('mortars', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u7802\u6d46\u77fc\u8bd5\u5757')),
                ('checkworks', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u590d\u6838\u8bb0\u5f55')),
                ('materialinfos', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u8fdb\u9000\u573a')),
                ('overtimes', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u52a0\u73ed\u4e0e\u505c\u5de5\u6e05\u7a7a')),
                ('others', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5176\u4ed6')),
                ('curr_time', models.DateField(blank=True, null=True, verbose_name='\u65e5\u671f')),
                ('pdffilepath', models.CharField(blank=True, max_length=256, null=True, verbose_name='pdf\u6587\u4ef6\u8def\u5f84')),
                ('engineering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Engineering', verbose_name='\u5de5\u7a0b')),
            ],
            options={
                'ordering': ('-curr_time',),
                'db_table': 'diary_record',
                'verbose_name': '\u65bd\u5de5\u65e5\u8bb0',
                'verbose_name_plural': '\u65bd\u5de5\u65e5\u8bb0',
            },
        ),
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.IntegerField(blank=True, default=1, verbose_name='\u56fe\u7247\u7c7b\u578b')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Document', verbose_name='\u6587\u4ef6')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Record', verbose_name='\u5371\u5927')),
            ],
            options={
                'db_table': 'diary_Recordfile',
                'verbose_name': '\u65e5\u8bb0\u6587\u4ef6',
                'verbose_name_plural': '\u65e5\u8bb0\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='RecordWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5206\u90e8\u540d\u79f0')),
                ('designwork', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u9884\u8ba1\u5de5\u4f5c\u91cf')),
                ('completework', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5b9e\u9645\u5de5\u4f5c\u91cf')),
                ('content', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewordworks', to='Projects.Record', verbose_name='\u65e5\u8bb0')),
            ],
            options={
                'db_table': 'diary_record_work',
                'verbose_name': '\u5206\u90e8\u5185\u5bb9',
                'verbose_name_plural': '\u5206\u90e8\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='RecordWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u540d\u79f0')),
                ('monitor', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u73ed\u7ec4')),
                ('peoples', models.IntegerField(blank=True, default=0, verbose_name='\u4eba\u6570')),
                ('recordwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewordworktypes', to='Projects.RecordWork', verbose_name='\u5206\u90e8')),
            ],
            options={
                'db_table': 'diary_record_work_type',
                'verbose_name': '\u5de5\u79cd',
                'verbose_name_plural': '\u5de5\u79cd',
            },
        ),
        migrations.AddField(
            model_name='jsfa',
            name='PrjSys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jsfa', to='Projects.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='jsfa',
            name='branch_engeering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.BranchEngineering', verbose_name='\u6240\u5c5e\u5206\u9879'),
        ),
        migrations.AddField(
            model_name='jsfa',
            name='engineering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineerdangers', to='Projects.Engineering', verbose_name='\u6240\u5c5e\u5de5\u7a0b'),
        ),
        migrations.AddField(
            model_name='engineering',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineertlist', to='Projects.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
