# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineering',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5de5\u671f'),
        ),
    ]
